### ISSUE TITLE
td.replace(path) is relative to the setupTestFrameworkScriptFile not the path of the test

### ISSUE THREAD

**Issue by skbolton** [testdouble/testdouble-jest#2]
I will do some more digging to see what is going on but wanted to give you a heads up in case you know anything about this. 

I was getting really weird behavior when trying to `td.replace()` in my test. Here is the situation. I am currently writing a test for `model.js` that needs to mock a dependency it has on `query.js`. The test is happening in `__test__/model.test.js`
<img width="234" alt="screen shot 2018-03-11 at 10 38 54 pm" src="https://user-images.githubusercontent.com/13260877/37266185-3deb40f4-257e-11e8-8bc8-9d0d14f20f19.png">

Here is the setup of my test
<img width="837" alt="screen shot 2018-03-11 at 10 49 08 pm" src="https://user-images.githubusercontent.com/13260877/37266227-75632a56-257e-11e8-9fc7-ad58d8473484.png">

I get the following error. `jestSetup.js` is my SetupTestFrameworkScriptFile:
<img width="1040" alt="screen shot 2018-03-11 at 10 50 11 pm" src="https://user-images.githubusercontent.com/13260877/37266261-b6c16170-257e-11e8-9f89-d1eba6edd40c.png">

As soon as I change the `td.replace()` path relative to that setup file things work
<img width="747" alt="screen shot 2018-03-11 at 10 48 33 pm" src="https://user-images.githubusercontent.com/13260877/37266275-cdec356e-257e-11e8-8ba6-48c3d11d4969.png">

<img width="676" alt="screen shot 2018-03-11 at 10 52 22 pm" src="https://user-images.githubusercontent.com/13260877/37266291-e9852e20-257e-11e8-9efe-b67462efc03b.png">

Here is my package.json for completeness 
```
{
  "name": "arbiter-salesforce",
  "version": "0.1.1",
  "description": "A Salesforce ORM powered by jsforce",
  "main": "index.js",
  "tonicExample": "const arbiter = require('arbiter-salesforce')",
  "repository": {
    "type": "git",
    "url": "git://github.com/skbolton/Arbiter"
  },
  "scripts": {
    "test": "standard && jest",
    "fix": "standard --fix"
  },
  "jest": {
    "setupTestFrameworkScriptFile": "test/jestSetup.js"
  },
  "keywords": [],
  "author": "Stephen Bolton",
  "license": "ISC",
  "standard": {
    "env": "jest",
    "globals": [
      "td",
      "specify"
    ]
  },
  "devDependencies": {
    "jest": "^22.4.2",
    "rimraf": "^2.6.1",
    "standard": "^10.0.2",
    "testdouble": "^3.5.2",
    "testdouble-jest": "^1.0.1"
  },
  "dependencies": {
    "dot-prop": "^4.1.1",
    "jsforce": "^1.8.0",
    "superstruct": "^0.5.1",
    "type-detect": "^4.0.0"
  }
}
```
Sorry for the dump of images I just thought they show some things better

**Comment by skbolton** [comment]
After a little more digging it is reproducible by changing the setupTestFrameworkScriptFile in the example code in this repo to being different from the folder the tests are in.

**Comment by searls** [comment]
Thanks for the report @skbolton, it turns out you are exactly correct!

The issue appears to be that `jest.requireActual` resolves the path relative to the file from which it is called (the helper, in this case), which of course will be the Wrong Thing from the perspective of almost every Jest test.

I just spent about an hour digging through the source and attempting to see if I could use a similar trick to what we do in [quibble](https://github.com/testdouble/quibble), but then realized that finding the caller's location using stack traces isn't quite possible due to the way Jest runs every test in a v8 VM instance.

It's a shame that jest does not expose more of its `LocalModuleRequire` goodies (like its `resolve` function), because it'd probably make this a lot easier. (What is [actually exported](https://github.com/facebook/jest/blob/master/packages/jest-runtime/src/index.js#L827-L828) and [what is available](https://github.com/facebook/jest/blob/23eec748db0de7b6b5fcda28cc51c48ddae16545/packages/jest-runtime/src/index.js#L694-L700).

I wonder if Jest's runner offers any way to get the absolute path of the currently running test. If we had that, we could use its directory to join whatever relative paths were passed in at least, which should work

**Comment by searls** [comment]
Ok, I think I have this fixed. This should work as of testdouble@3.6.0 and testdouble-jest@2.0.0

**Comment by searls** [comment]
I just created a test project using only the npm versions of testdouble, quibble, and testdouble-jest (prior to release  I had to use links which made me a little wary), and everything seems to work ok.

Hopefuly the mechanism used to absolutify paths works in all cases

**Comment by skbolton** [comment]
Sounds good. I did the same thing. Their source takes some serious time to digest and I got to that same module you are talking about. I will give the new versions a go. Thanks for tackling this!
